name: Generate Data Element Profiles

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
  
      - run: git clone https://github.com/open-data/deplane.git
      - run: pip install jsonschema
      - run: pip install pyyaml
      - run: cd deplane && python setup.py develop
      - run: sudo apt install gettext
      - run: make compile-mo
